# Generated by Django 4.2.29 on 2026-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='exp_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='player_tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='townhall_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='trophies',
            field=models.IntegerField(default=0),
        ),
    ]
