# Generated by Django 4.2.29 on 2026-04-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='cr_best_trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='cr_player_tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='cr_trophies',
            field=models.IntegerField(default=0),
        ),
    ]
