# Generated by Django 4.2.29 on 2026-04-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playerprofile_cr_best_trophies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='current_rank',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='win_rate',
        ),
    ]
